# Generated by Django 3.2.14 on 2022-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0003_alter_result_result_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='result_img',
        ),
        migrations.AddField(
            model_name='result',
            name='result_img_path',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
