# Generated by Django 3.2.14 on 2022-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0005_alter_result_result_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=250),
        ),
    ]
