# Generated by Django 3.2.14 on 2022-07-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cari', '0006_alter_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
